import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { FC } from "react";
import Navbar from "@/components/Navbar";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type LayoutProps = {
  children: Readonly<React.ReactNode>;
  params: { locale: "en" | "es" };
};

const RootLayout: FC<LayoutProps> = ({ children, params: { locale } }) => {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </NextIntlClientProvider>
    </html>
  );
};

export default RootLayout;
